### ISSUE TITLE
Navigator 레이아웃 적용 및 SCSS로 스타일링

### ISSUE THREAD

**Issue by Dropper-in** [NextTeamB/ONEHOUR#10]
# Navigator 레이아웃 적용 및 SCSS로 스타일링

## 목적
- 와이어프레임 디자인을 반영한 네비게이터 레이아웃 제작 및 적용
## To-do
- [x] 내비게이터 레이아웃 컴포넌트 작성
- [x] SCSS 사용을 위한 패키지 설치 및 적용
- [x] url 명세에 맞게 폴더명 rename

## 기타 참고 사항
-
