### ISSUE TITLE
유저 프로필 이미지 API 제반사항 작업

### ISSUE THREAD

**Issue by tennto** [NextTeamB/ONEHOUR#117]
# 제목
유저 프로필 이미지 API 제반사항 작업

## 목적
- 유저 프로필 이미지 API 제반사항 작업

## To-do

- [x] /users/image API 구현
- [x] 기존 유저 컬렉션 response data 표기 사항 수정
- [x] 서버 이미지 브라우저 마운트

## 기타 참고 사항

- 없음
