### ISSUE TITLE
Challengers 페이지 보수작업

### ISSUE THREAD

**Issue by tennto** [NextTeamB/ONEHOUR#128]
# 제목
Challengers 페이지 보수작업

## 버그 발생 사항
- 상세 게시물 이미지 linking 실패
- DB 데이터 동기화 (이미지 로드 실패) 미작업
- 빈 게시글 이미지 URL 상태처리 부재

## To-do

- [ ] 상세 게시물 이미지 링크 작업
- [ ] DB 데이터 동기화
- [ ] 빈 게시글 이미지 URL 상태처리

## 기타 참고 사항

-
