### ISSUE TITLE
내비게이션 바, 챌린저스, 로그인 반응형 뷰 구현

### ISSUE THREAD

**Issue by Dropper-in** [NextTeamB/ONEHOUR#156]
# 내비게이션 바, 챌린저스, 로그인 반응형 뷰 구현

## 목적

- 내비게이션 바, 챌린저스, 로그인 반응형 뷰 구현

## To-do

- [ ] 내비게이션 바 조건부 렌더링
- [ ] 챌린저스 grid 반응형 수정
- [ ] 로그인 및 회원가입 페이지 반응형 뷰 구현

## 기타 참고 사항

-
