### ISSUE TITLE
챌린지 시작 및 온고잉 페이지 제작

### ISSUE THREAD

**Issue by haesol822** [NextTeamB/ONEHOUR#17]
# 챌린지 시작 및 온고잉 페이지 제작

## 목적
-  챌린지 시작 페이지 제작, 온고잉 페이지 타이머 제작
## To-do
- [x] /challenge 페이지 디자인
- [x] /challenge/new 페이지 제작
- [x] /challenge/ongoing 페이지 제작 - 타이머
- [x] /challenge/ongoing 프로그레스 바 제작
- [x] /challenge/ongoing 텍스트박스 입력값 & 버튼 값 불러오기

## 기타 참고 사항
- 텍스트박스 입력값 & 버튼 값 불러오기 -> jotai 라이브러리 사용
