### ISSUE TITLE
챌린저스 게시판 및 게시글 작성 기능

### ISSUE THREAD

**Issue by haesol822** [NextTeamB/ONEHOUR#27]
# 챌린저스 게시판 및 게시글 작성 기능

## 목적
- 챌린저스 게시판 및 게시글 작성하기 기능 만들기

## To-do
- [ ] 챌린저스 게시판 작업
- [ ] 챌린저스 게시판에서 게시글 띄우기
- [ ] 챌린저스 게시글 작성하기 기능 구현

## 기타 참고 사항
- 챌린저스 게시판 url -> /challengers로 작업 
- 챌린저스 게시글 작성하기 url -> /challengers/post로 작업

**Comment by tennto** [comment]
머지했는데 커맨드가 안먹히네요 클로즈 하겠습니다!!
