### ISSUE TITLE
Axios 기타 메서드 테스팅

### ISSUE THREAD

**Issue by tennto** [NextTeamB/ONEHOUR#29]
# 제목
Axios 기타 메서드 테스팅
## 목적
- Axios 기타 메서드 테스팅 (DELETE / PATCH / PUT)
## To-do
- [ ] DELETE 메서드 테스팅
- [ ] PATCH 메서드 테스팅
- [ ] PUT 메서드 테스팅

## 기타 참고 사항
- 테스팅 완료 후 기타 페이지 제작들어가겠습니다
