### ISSUE TITLE
데이터베이스 연동과 로그인 관련 API 구현

### ISSUE THREAD

**Issue by tennto** [NextTeamB/ONEHOUR#36]
# 제목
데이터베이스 연동과 로그인 관련 API 구현
## 목적
- /login, /sign-up 페이지에 DB 데이터를 이용한  이메일 인증 로직과 회원가입 로직 구현 authorization 구현
- Silent Refresh 구현
- 로그아웃 로직 구현

## To-do
- [x] MongoDB Connection 관련 코드 파일 백업
- [x] /login/page.tsx 파일 내의 리다이렉션 url 수정 (/main -> /dashboard)
- [x] /main 디렉터리 리네임 (/dashboard)
- [x] jwt 라이브러리 사용하여 jwt 토큰 (access Token) 생성 후 API 응답 authorization 헤더로 설정하는 로직 구현
- [x] /api/users/login 경로 생성 후  페이지에서 로그인 요청 시 이메일 인증 로직 구현
- [x] MongoDB "userAccount" 컬렉션 내의 데이터 유저 정보로 수정
- [x] 리프레시 토큰 구현 및 리프레시 토큰 쿠키 설정
- [x] silent refresh 구현하여 로그인 유지 처리 구현
- [x] 로그아웃 API 요청 응답 완료 후 페이지 리다이렉션

## 기타 참고 사항
- 완료 후 이어서 /api/auth/refresh & /api/auth/logout API 구현하겠습니다
