### ISSUE TITLE
챌린지 페이지 API 구현 및 DB 데이터 Redux 연동

### ISSUE THREAD

**Issue by tennto** [NextTeamB/ONEHOUR#44]
# 제목
챌린지 페이지 API 구현 및 DB 데이터 Redux 연동
## 목적
- 챌린지 페이지 API 구현 및 DB 데이터 Redux 연동
## To-do
- [x] 챌린지 페이지 유저 데이터 POST API 구현
- [x] 챌린지 페이지 유저 데이터 GET API 구현
- [x] Redux 유저 데이터 저장 구현
- [x] AC Token 작업 사항 merge
- [x] 로그인 페이지 Redux 유저 데이터 저장 구현
- [x] refresh API 점검

## 기타 참고 사항
- 챌린지 페이지 작업 후 이어서 settings 페이지 작업합니다
