### ISSUE TITLE
유저정보 API 구현 작업

### ISSUE THREAD

**Issue by tennto** [NextTeamB/ONEHOUR#49]
# 제목
유저정보 API 구현 작업

## 목적
- 유저정보 API 구현 작업 (회원탈퇴 / 이메일 중복 확인 / 비밀번호 변경 / 닉네임 변경)

## To-do
- [x] 회원탈퇴 API 구현
- [x] 이메일 중복 확인 API 구현
- [x] 비밀번호  변경 API 구현
- [x] 닉네임 변경 API 구현

## 기타 참고 사항
-
