### ISSUE TITLE
Settings 페이지 작업

### ISSUE THREAD

**Issue by tennto** [NextTeamB/ONEHOUR#52]
# 제목
Settings 페이지 작업

## 목적
- Settings 페이지 ui 구성 및 API 연동

## To-do
- [x] UI 작업
- [x] 닉네임 변경 API 연동
- [x] 비밀번호 변경 API 연동
- [x] 회원탈퇴 API 연동

## 기타 참고 사항
- 리프레시 토큰 고쳐져랏..!

**Comment by tennto** [comment]
#49 이슈와 함께 클로징합니다
