### ISSUE TITLE
challenges 페이지 크기 수정

### ISSUE THREAD

**Issue by haesol822** [NextTeamB/ONEHOUR#60]
# challenges 페이지 크기 수정 및 레코즈 UI

## 버그 발생 사항
- challenges 페이지 비율 수정
## To-do
- [x] /challenges 페이지 크기 수정
- [x] 챌린지 완료 시 로티 수정
- [x] /records 페이지 프로그레스 바 구현 작업

## 기타 참고 사항
-
