### ISSUE TITLE
info페이지 url 통일 및 페이지 애니메이션 적용

### ISSUE THREAD

**Issue by haesol822** [NextTeamB/ONEHOUR#96]
# info페이지 url 통일 및 페이지 애니메이션 적용

## 목적

- info 페이지 컴포넌트 처리 및 깔끔한 애니메이션으로 구현

## To-do

- [x] info페이지 url 통일
- [x] 페이지 애니메이션 적용
- [ ] 미디어 쿼리 반영

## 기타 참고 사항

-
